// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleIAM.OpenIdAuthority.Entities;

namespace SimpleIAM.OpenIdAuthority.Migrations.Migrations
{
    [DbContext(typeof(OpenIdAuthorityDbContext))]
    partial class OpenIdAuthorityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleIAM.OpenIdAuthority.Entities.OneTimeCode", b =>
                {
                    b.Property<string>("SentTo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(254);

                    b.Property<DateTime>("ExpiresUTC");

                    b.Property<int>("FailedAttemptCount");

                    b.Property<string>("LongCodeHash");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(2048);

                    b.Property<string>("ShortCodeHash");

                    b.HasKey("SentTo");

                    b.ToTable("OneTimeCodes");
                });

            modelBuilder.Entity("SimpleIAM.OpenIdAuthority.Entities.PasswordHash", b =>
                {
                    b.Property<string>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<int>("FailedAttemptCount");

                    b.Property<string>("Hash")
                        .IsRequired();

                    b.Property<DateTime>("LastChangedUTC");

                    b.Property<DateTime?>("TempLockUntilUTC");

                    b.HasKey("SubjectId");

                    b.ToTable("PasswordHashes");
                });

            modelBuilder.Entity("SimpleIAM.OpenIdAuthority.Entities.User", b =>
                {
                    b.Property<string>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.HasKey("SubjectId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimpleIAM.OpenIdAuthority.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("Type");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("SimpleIAM.OpenIdAuthority.Entities.UserClaim", b =>
                {
                    b.HasOne("SimpleIAM.OpenIdAuthority.Entities.User")
                        .WithMany("Claims")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
