// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SimpleIAM.PasswordlessLogin.Entities;
using System;

namespace SimpleIAM.PasswordlessLogin.Migrations.Migrations
{
    [DbContext(typeof(PasswordlessLoginDbContext))]
    [Migration("20180420155726_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleIAM.PasswordlessLogin.Entities.OneTimePassword", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(254);

                    b.Property<DateTime>("ExpiresUTC");

                    b.Property<string>("LinkCode")
                        .HasMaxLength(36);

                    b.Property<string>("OTP")
                        .HasMaxLength(8);

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(2048);

                    b.HasKey("Email");

                    b.ToTable("OneTimePasswords");
                });

            modelBuilder.Entity("SimpleIAM.PasswordlessLogin.Entities.PasswordHash", b =>
                {
                    b.Property<string>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<int>("FailedAuthenticationCount");

                    b.Property<string>("Hash")
                        .IsRequired();

                    b.Property<DateTime>("LastChangedUTC");

                    b.Property<DateTime>("TempLockUntilUTC");

                    b.HasKey("SubjectId");

                    b.ToTable("PasswordHashes");
                });

            modelBuilder.Entity("SimpleIAM.PasswordlessLogin.Entities.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.HasKey("SubjectId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
